apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: tomcat-deployment-template
  title: Tomcat Deployment on Minikube with ArgoCD
  description: Scaffolds a project to deploy a Tomcat application on Minikube using ArgoCD
spec:
  owner: your-team
  type: service
  parameters:
    - title: Application Configuration
      required:
        - name
        - githubOrg
      properties:
        name:
          type: string
          title: Application Name
          description: Unique name for the Tomcat application
        githubOrg:
          type: string
          title: GitHub Organization/User
          description: The GitHub organization or user where the repository will be created
  steps:
    - id: scaffold
      name: Scaffold Files
      action: fetch:cookiecutter
      input:
        url: https://github.com/yellowjung/backstage_catalog.git
        directory: /skeleton
        values:
          name: '{{ parameters.name }}'
    - id: createRepo
      name: Create GitHub Repository
      action: publish:github
      input:
        org: '{{ parameters.githubOrg }}'
        name: '{{ parameters.name }}'
        private: false
        files:
          - path: deployment.yaml
          - path: service.yaml
          - path: argocd-app.yaml
  output:
    links:
      - url: https://github.com/{{ parameters.githubOrg }}/{{ parameters.name }}
        title: View the GitHub Repository
      - url: https://argocd.yourdomain.com/applications/{{ parameters.name }}
        title: View the Application in ArgoCD