apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: tomcat-deployment-template
  title: Tomcat Deployment on Minikube with ArgoCD
  description: Scaffolds a project to deploy a Tomcat application on Minikube using ArgoCD
  tags:
    - tomcat
    - argocd
spec:
  owner: youngdon
  type: service
  parameters:
    - title: Application Configuration
      required:
        - name
        - githubOrg
      properties:
        name:
          type: string
          title: Application Name
          description: Unique name for the Tomcat application
        githubOrg:
          type: string
          title: GitHub Organization/User
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
          description: The GitHub organization or user where the repository will be created
  steps:
    - id: teamplate
      name: Scaffold Files
      action: fetch:template
      input:
        url: https://github.com/yellowjung/backstage_catalog.git
        directory: skeleton
        values:
          name: '${{ parameters.name }}'
    
    - id: createRepo
      name: Create GitHub Repository
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: this is ${{ parameters.name }} deploy
        org: '${{ parameters.githubOrg }}'
        name: '${{ parameters.name }}'
        repoUrl: 'github.com/${{ parameters.githubOrg }}/${{ parameters.name }}'
        defaultBranch: main
        repoVisibility: public
        files:
          - path: deployment.yaml
          - path: service.yaml
          - path: argocd-app.yaml
  output:
    links:
      - url: https://github.com/${{ parameters.githubOrg }}/${{ parameters.name }}
        title: View the GitHub Repository
      - url: https://localhost:8080/applications/${{ parameters.name }}
        title: View the Application in ArgoCD