apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ parameters.name }}-tomcat
spec:
  project: default
  source:
    repoURL: 'https://github.com/{{ parameters.githubOrg }}/{{ parameters.name }}'
    path: .
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true