apiVersion: v1
kind: Service
metadata:
  name: ${{ parameters.name }}-tomcat-service
spec:
  type: NodePort
  selector:
    app: ${{ parameters.name }}-tomcat
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080